FROM node:20-alpine AS development
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
ENV CHOKIDAR_USEPOLLING=true
EXPOSE 5173 24678
CMD ["pnpm","run","dev","--host","0.0.0.0","--port","5173"]