services:
  api:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv

  web:
    image: node:20-alpine
    working_dir: /web
    volumes:
      - ./frontend:/web
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - api
