services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - PYTHONPATH=/app

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    depends_on:
      - api
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - fe_node_modules:/app/node_modules
    command: >
      sh -lc "pnpm install &&
              pnpm run dev --host 0.0.0.0 --port 5173"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  fe_node_modules:
